#!/bin/sh
clear
sleep 0.2
if [[ $(id -u) -ne 0 ]] ; then echo "convert2tau Must Run as Superuser." ; exit 1 ; fi
echo "Program for Converting RPM-OSTree systems to tauOS"
echo "(C) 2022 Innatical, LLC"
echo "THIS PROGRAM COMES WITH ABSOLUTELY NO WARRANTY. INNATICAL LLC IS NOT RESPONSIBLE FOR DAMAGE TO NETWORKS OR SYSTEMS."
read -p "Press Any Key To Confirm, Ctrl+C to exit"
sleep 0.2
echo "Adding Flatpak Applications"
#Flatpak apps - Production Ready
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
echo "Skipping org.gnome.TextEditor - Favor Nightly for now"
#flatpak install flathub org.gnome.TextEditor -y Favor Nightly for now
flatpak install flathub de.haeckerfelix.Shortwave -y
flatpak install flathub io.github.lainsce.Notejot -y
flatpak install flathub org.gnome.Geary -y
flatpak install flathub org.gnome.Podcasts -y
flatpak install flathub org.gnome.Music -y
flatpak install flathub org.gnome.PowerStats -y
#Development tools/Prerelease Software - Remove in production
flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
flatpak install flathub org.gnome.Extensions -y
flatpak install gnome-nightly org.gnome.TextEditor -y
echo "Skipping org.gnome.Builder - Remove in Prod"
#flatpak install flathub org.gnome.Builder -y
echo "Skipping fyi.zoey.Boop-GTK - Remove in Prod"
#flatpak install flathub fyi.zoey.Boop-GTK -y
echo "Skipping com.jetbrains.GoLand - Remove in Prod"
#flatpak install flathub com.jetbrains.GoLand -y
echo "Adding OSTree Remote..."
ostree remote add --no-gpg-verify tau https://innatical-tau.sfo3.digitaloceanspaces.com/
echo "Done"
sleep 0.2
echo "Rebasing..."
rpm-ostree rebase tau:tau/desktop/x86_64/stable
echo "Done"
sleep 0.2
clear
read -p "Press Any Key to Finish Installation and Reboot"
systemctl reboot


