#!/bin/sh
clear

echo "THIS PROGRAM COMES WITH ABSOLUTELY NO WARRANTY. FYRA LABS IS NOT RESPONSIBLE FOR DAMAGE TO NETWORKS OR SYSTEMS."

echo "Setting up Flatpak remotes"
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-add --if-not-exists catalogue https://repo.tauos.co/catalogue.flatpakrepo
echo "Installing flatpaks"
flatpak install flathub org.gnome.TextEditor -y
flatpak install flathub de.haeckerfelix.Shortwave -y 
flatpak install flathub io.github.lainsce.Notejot -y 
flatpak install flathub org.gnome.Geary -y 
flatpak install flathub org.gnome.Podcasts -y 
flatpak install flathub org.gnome.Music -y 
flatpak install flathub org.gnome.PowerStats -y
#Development tools/Prerelease Software - Remove in production
echo "Setting up GNOME Nightly remote"
flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo >&-
echo "Installing Flatpaks"
flatpak install flathub org.gnome.Extensions -y
flatpak install gnome-nightly org.gnome.TextEditor -y
flatpak install gnome-nightly org.gnome.Builder -y
flatpak install flathub fyi.zoey.Boop-GTK -y
echo "Adding tauOS OSTree remote"
ostree remote add --no-gpg-verify tau https://repo.tauos.co/ostree
rpm-ostree rebase tau:tau/home/1.1/x86_64
#systemctl reboot
